name: Deploy Tracker to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install terser for minification
        run: npm install -g terser

      - name: Create minified version
        run: terser tracker.js --compress --mangle --output tracker.min.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy tracker.js to S3
        run: |
          aws s3 cp tracker.js s3://pf-pixel-tag/tracker.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

      - name: Deploy tracker.min.js to S3
        run: |
          aws s3 cp tracker.min.js s3://pf-pixel-tag/tracker.min.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

      - name: Deploy storage-layer files to S3
        run: |
          # Deploy JavaScript files
          aws s3 cp storage-layer/client.js s3://pf-pixel-tag/storage-layer/client.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

          aws s3 cp storage-layer/client.min.js s3://pf-pixel-tag/storage-layer/client.min.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

          aws s3 cp storage-layer/hub.js s3://pf-pixel-tag/storage-layer/hub.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

          aws s3 cp storage-layer/hub.min.js s3://pf-pixel-tag/storage-layer/hub.min.js \
            --content-type "application/javascript" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

          # Deploy HTML file
          aws s3 cp storage-layer/hub.html s3://pf-pixel-tag/storage-layer/hub.html \
            --content-type "text/html" \
            --cache-control "public, max-age=300" \
            --metadata-directive REPLACE

      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E25L56VGAU6FC \
            --paths "/tracker.js" "/tracker.min.js" "/storage-layer/*"
